### PR TITLE
Create Koala_Bin_Reader.java

### PR DESCRIPTION
**Pull request by jejmule**
Plugin to read Koala Binary File
This files are used by Digital Holographic Microscope.

### CODE REVIEW

**Comment by dscho** [comment]
Ah, so this is where the reader is. It seems #1 was a bit premature, yes?

**Comment by jejmule** [comment]
Hello,
I am new to github and make two forks instead of one, I am sorry about that.
1. I can clean the code but I need some instructions to do that, I am not software engineer by formation.
2. Please find bellow the specifications about the format we provide in the manual : 
Test images download link  : http://lyncee1.epfl.ch/~marketing/JPA/test-img.zi

5.2.2 Phase .bin files format:
The extension .bin stands for binary file. This file type is less consuming in
term of disk space, but contain the same information. It is not possible to read
it with text editors. Here below is the format and an exemple of Matlab code
to read them.
header:
header version
endianness (depends of system type)
header size (23 bytes)
width
height
pixel size
height conversion
unit code (radians or meters)
data:
binary values

I am open to any comment/suggestions  to improve my code

**Comment by dscho** [comment]
> http://lyncee1.epfl.ch/~marketing/JPA/test-img.zi

That link yields a 404 for me...

> I can clean the code but I need some instructions to do that

I recently wrote up instructions how to clean up code for a related project. Please find them [here](https://github.com/maven-nar/nar-maven-plugin/wiki/How-to-contribute). If the instructions are not clear enough, I would appreciate it if you pointed out the flaws and improved the documentation based on my response.

> 5.2.2 Phase .bin files format:

This looks like taken from a manual. Is that manual online? If yes, it would be good to include a link in the commit message, for future record.

> Here below is the format and an exemple of Matlab code
> to read them.

Could you provide the link to the Matlab code, please?

**Comment by jejmule** [comment]
The p of ziP was missing : http://lyncee1.epfl.ch/~marketing/JPA/test-img.zip

I will take a look to the instruction and clean the code

There is no online version of the manual. Please find bellow the matlab code

Matlab code for reading .bin files:
/*
byte header version
byte endianness (0=little endian, 1=big endian)
int header size (in bytes) (including the header and endianness bytes)
int width
int height
float pxsize (in um)
float hconv (height conversion factor -> m)
byte unit code
*/
int=4bytes, float=4bytes
function [a, w, h]=read mat bin(fname)
% Reading binary file
fid = fopen(fname,’rb’);
head vers = fread(fid,1,’int8’);
endianness = fread(fid,1,’int8’);
head size = fread(fid,1,’int32’);
w = fread(fid,1,’int32’);
h = fread(fid,1,’int32’);
pxsize = fread(fid,1,’float32’);% in m
hconv = fread(fid,1,’float32’);% height conversion factor, multiply values by
this factor to get meters
unit code = fread(fid,1,’int8’);% 1=>rad 2=>meter
tmp = fread(fid,[w,h],’float32’);
a = tmp’;
fclose(fid);

**Comment by dscho** [comment]
That looks promising! Please include the Matlab code (in lieu of a link to an official spec) into the commit message.

**Comment by dscho** [comment]
Oh, and it would be good to also include the link http://www.lynceetec.com/koala-acquisition-analysis/ so that interested parties would know what this Koala thing is all about (apart from being a cute animal eating only one specific plant's leaves).

**Comment by dscho** [comment]
@jejmule any chance you can finalize this PR?

**Comment by ctrueden** [comment]
@jejmule I took the liberty of cleaning up this PR, along with PR #1. That branch is now merged to master; see 1ddc85413260137f88fd87d0bd47a298e921bd04. Thank you very much for your contribution!

**Comment by ctrueden** [comment]
I just released [IO_ version 2.2.0](https://github.com/fiji/IO/releases/tag/IO_-2.2.0) which includes this contribution, and uploaded it to the Fiji update site. Cheers.

**Pull request closed without merging**
